src/Entity/BrickItem.php
<?php

namespace App\Entity;

use App\Repository\BrickItemRepository;
use App\Service\BrickLink;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: BrickItemRepository::class)]
class BrickItem
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 255)]
    private $no;

    #[ORM\Column(type: 'string', length: 255)]
    private $name;

    #[ORM\Column(type: 'string', length: 255)]
    private $type;

    #[ORM\Column(type: 'integer')]
    private $category_id;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $alternate_no;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $image_url;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $thumbnail_url;

    #[ORM\Column(type: 'float', nullable: true)]
    private $weight;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $dim_x;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $dim_y;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $dim_z;

    #[ORM\Column(type: 'integer', nullable: true)]
    private $year_released;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $description;

    #[ORM\Column(type: 'boolean', nullable: true)]
    private $is_obsolete;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $language_code;

    #[ORM\OneToMany(mappedBy: 'Item', targetEntity: Inventory::class)]
    private $inventories;

    public function __construct()
    {
        $this->inventories = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNo(): ?string
    {
        return $this->no;
    }

    public function setNo(string $no): self
    {
        $this->no = $no;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(string $type): self
    {
        $this->type = $type;

        return $this;
    }

    public function getCategoryId(): ?int
    {
        return $this->category_id;
    }

    public function setCategoryId(int $category_id): self
    {
        $this->category_id = $category_id;

        return $this;
    }

    public function getAlternateNo(): ?string
    {
        return $this->alternate_no;
    }

    public function setAlternateNo(string $alternate_no): self
    {
        $this->alternate_no = $alternate_no;

        return $this;
    }

    public function getImageUrl(): ?string
    {
        return $this->image_url;
    }

    public function setImageUrl(?string $image_url): self
    {
        $this->image_url = $image_url;

        return $this;
    }

    public function getThumbnailUrl(): ?string
    {
        return $this->thumbnail_url;
    }

    public function setThumbnailUrl(?string $thumbnail_url): self
    {
        $this->thumbnail_url = $thumbnail_url;

        return $this;
    }

    public function getWeight(): ?float
    {
        return $this->weight;
    }

    public function setWeight(?float $weight): self
    {
        $this->weight = $weight;

        return $this;
    }

    public function getDimX(): ?string
    {
        return $this->dim_x;
    }

    public function setDimX(?string $dim_x): self
    {
        $this->dim_x = $dim_x;

        return $this;
    }

    public function getDimY(): ?string
    {
        return $this->dim_y;
    }

    public function setDimY(?string $dim_y): self
    {
        $this->dim_y = $dim_y;

        return $this;
    }

    public function getDimZ(): ?string
    {
        return $this->dim_z;
    }

    public function setDimZ(?string $dim_z): self
    {
        $this->dim_z = $dim_z;

        return $this;
    }

    public function getYearReleased(): ?int
    {
        return $this->year_released;
    }

    public function setYearReleased(?int $year_released): self
    {
        $this->year_released = $year_released;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function isIsObsolete(): ?bool
    {
        return $this->is_obsolete;
    }

    public function setIsObsolete(?bool $is_obsolete): self
    {
        $this->is_obsolete = $is_obsolete;

        return $this;
    }

    public function getLanguageCode(): ?string
    {
        return $this->language_code;
    }

    public function setLanguageCode(?string $language_code): self
    {
        $this->language_code = $language_code;

        return $this;
    }

    /**
     * @return Collection<int, Inventory>
     */
    public function getInventories(): Collection
    {
        return $this->inventories;
    }

    public function addInventory(Inventory $inventory): self
    {
        if (!$this->inventories->contains($inventory)) {
            $this->inventories[] = $inventory;
            $inventory->setItem($this);
        }

        return $this;
    }

    public function removeInventory(Inventory $inventory): self
    {
        if ($this->inventories->removeElement($inventory)) {
            // set the owning side to null (unless already changed)
            if ($inventory->getItem() === $this) {
                $inventory->setItem(null);
            }
        }

        return $this;
    }
    
}

src/Controller/InventoryController.php
<?php

namespace App\Controller;

use App\Entity\Inventory;
use App\Entity\BrickItem;
use App\Htpp\HttpHandle;
use App\Repository\InventoryRepository;
use App\Repository\BrickItemRepository;
use App\Service\BrickLink;

use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpClient\HttpClient;
use Symfony\Contracts\HttpClient\HttpClientInterface;

#[Route('/inventory')]
class InventoryController extends AbstractController
{

	#[Route('/', name: 'app_inventory')]
    public function index(): Response 
	{
        return $this->render('inventory/index.html.twig', [
            'controller_name' => 'InventoryController',
        ]);
    }

    #[Route('/new', name: 'app_inventory_new')]
    public function new(InventoryRepository $inventoryRepository): Response
    {
		//For test purposes
        $json = '{
			"inventory_id": 294632795,
			"item": {
				"no": "2357",
				"name": "Brick 2 x 2 Corner",
				"type": "PART",
				"category_id": 5
			},
			"color_id": 5,
			"color_name": "Red",
			"quantity": 4,
			"new_or_used": "N",
			"unit_price": "0.6300",
			"bind_id": 0,
			"description": "",
			"remarks": "0590",
			"bulk": 1,
			"is_retain": false,
			"is_stock_room": false,
			"date_created": "2022-04-28T04:00:00.000Z",
			"my_cost": "0.0000",
			"sale_rate": 25,
			"tier_quantity1": 0,
			"tier_price1": "0.0000",
			"tier_quantity2": 0,
			"tier_price2": "0.0000",
			"tier_quantity3": 0,
			"tier_price3": "0.0000",
			"my_weight": "0.0000"
		}';

        $inventory = new Inventory($json);

        $inventoryRepository->add($inventory, true);

        return new Response('Saved new inventory with id '.$inventory->getId());
    }

	#[Route('/show/{id}', name: 'app_inventory_show')]
    public function show(InventoryRepository $inventoryRepository, int $id): Response
	{

		$inventory = $inventoryRepository->find($id);

        return $this->render('inventory/show.html.twig', [
            'controller_name' => 'InventoryController',
            'inventory' => $inventory,
        ]);
    }
	

	#[Route('/pull', name: 'app_inventory_pull')]
    public function pull(InventoryRepository $inventoryRepository, BrickItemRepository $itemRepository, BrickLink $api): Response 
	{
		$error = "";
		// // setup api request
		//$httpHandle = new HttpHandle(HttpClient::create());

		// // fetch items
		//$response = $httpHandle->fetchBrickLinkInventory();

		// // decode json respone to php array
		//$response_json = json_decode($response, true);
		$response_json = $api->getInventories();

		if ($response_json['meta']['code'] !== 200)
		{
			$error = array('message' => $response_json['meta']['message'], 'description' => $response_json['meta']['description']);
			return $this->render('inventory/pull.html.twig', [
				'controller_name' => 'InventoryController',
				'error' => $error,
			]);
		}

		// for counting updated records
		$updated_items = 0;
		$updated_invs = [];

		// processing all inventories from request
		foreach ($response_json['data'] as $key => $value) {
			// check if item exist in database
			$find_item = $itemRepository->findOneBy(['no' => $value['item']['no']]);
			if (!$find_item)
			{
				// if not create
				$item = new BrickItem();
				$item->setNo($value['item']['no']);
				$item->setName($value['item']['name']);
				$item->setType($value['item']['type']);
				$item->setCategoryId($value['item']['category_id']);

				$itemRepository->add($item, true);
				$updated_items++;
			} else {
				// if exist ignore
				$item = $find_item;
			}

			// check if inventory with that id already exist
			$find_inventory = $inventoryRepository->findOneBy(['inventoryId' => $value['inventory_id']]);
			$inventory = new Inventory();
			$inventory->setInventoryId($value['inventory_id']);
			$inventory->setItem($item);
			if (strcmp($item->getType(), 'SET') == 0) {
				$inventory->setCompleteness('completeness');
			}
			$inventory->setColorId($value['color_id']);
			$inventory->setColorName($value['color_name']);
			$inventory->setQuantity($value['quantity']);
			$inventory->setNewOrUsed($value['new_or_used']);
			$inventory->setUnitPrice($value['unit_price']);
			$inventory->setBindId($value['bind_id']);
			$inventory->setDescription($value['description']);
			$inventory->setRemarks($value['remarks']);
			$inventory->setBulk($value['bulk']);
			$inventory->setIsRetain($value['is_retain']);
			$inventory->setIsStockRoom($value['is_stock_room']);
			$inventory->setDateCreated(new \DateTime($value['date_created']));
			$inventory->setMyCost($value['my_cost']);
			$inventory->setSaleRate($value['sale_rate']);
			$inventory->setTierQuantity1($value['tier_quantity1']);
			$inventory->setTierPrice1($value['tier_price1']);
			$inventory->setTierQuantity2($value['tier_quantity2']);
			$inventory->setTierPrice2($value['tier_price2']);
			$inventory->setTierQuantity3($value['tier_quantity3']);
			$inventory->setTierPrice3($value['tier_price3']);
			$inventory->setMyWeight($value['my_weight']);
			if(!$find_inventory)
			{
				// if not create

				$inventoryRepository->add($inventory, true);
				// $updated_invs++;
				array_push($updated_invs, [null, $inventory]);
			} else {
				// otherwise assign
				$old_inv = clone $find_inventory;
				if ($find_inventory->update($inventory))
				{
					// it will update inventory
					$inventoryRepository->add($find_inventory, true);
					// $updated_invs++;
					array_push($updated_invs, [$old_inv, $find_inventory]);
				}
				// $inventory = $find_inventory;
			}
		}

        return $this->render('inventory/pull.html.twig', [
            'controller_name' => 'InventoryController',
            // 'response' => $inventoryRepository->findAll(),
			'error' => '',
			'updated_items' => $updated_items,
			'updated_invs' => count($updated_invs),
			'inventories' => $updated_invs,
			'added' => null,
			'updated' => null,
			'removed' => null,
        ]);
    }

	#[Route('/pull2', name: "app_inventory_pull2")]
	public function pull2(InventoryRepository $inventoryRepository, BrickItemRepository $itemRepository, BrickLink $api): Response
	{
		$error = "";

		$response_json = $api->getInventories();

		if ($response_json['meta']['code'] !== 200)
		{
			$error = array('message' => $response_json['meta']['message'],
						   'description' => $response_json['meta']['description']);

			return $this->render('inventory/pull.html.twig', [
				'controller_name' => 'InventoryController',
				'error' => $error,
			]);
		}

		// some stats
		$updated_items = 0;
		$inv_added = [];
		$inv_updated = [];
		$inv_removed = [];

		// important for json processing
		$item_list = [];
		$item_id_list = [];
		$inventory_list = [];
		$inventory_id_list = [];

		// processing items
		for ($i=0; $i < count($response_json['data']); $i++)
		{
			$value = $response_json['data'][$i];

			$item = new BrickItem();
			$item->setNo($value['item']['no']);
			$item->setName($value['item']['name']);
			$item->setType($value['item']['type']);
			$item->setCategoryId($value['item']['category_id']);
			if (!array_key_exists($value['item']['no'], $item_list))
			{
				$item_list[$value['item']['no']] = $item;
				array_push($item_id_list, $value['item']['no']);
			}
		}

		$db_item_list = $itemRepository->findAll(); // get all items from db

		foreach ($item_list as $key => $value)
		{
			$found = false;
			for ($i=0; $i < count($db_item_list); $i++)
			{
				if ($item_list[$key]->getNo() === $db_item_list[$i]->getNo())
				{
					$found = true;
					$item_list[$key] = $db_item_list[$i];
					break;
				}
			}
			if (!$found)
			{
				$itemRepository->add($item_list[$key]);
				$updated_items++;
			}
		}

		$itemRepository->flush();

		// processing invs
		for ($i=0; $i < count($response_json['data']); $i++)
		{
			$value = $response_json['data'][$i];
			$item = $item_list[$value['item']['no']];

			$inventory = new Inventory();
			$inventory->setInventoryId($value['inventory_id']);
			$inventory->setItem($item);
			if (strcmp($item->getType(), 'SET') == 0)
			{
				$inventory->setCompleteness('completeness');
			}
			$inventory->setColorId($value['color_id']);
			$inventory->setColorName($value['color_name']);
			$inventory->setQuantity($value['quantity']);
			$inventory->setNewOrUsed($value['new_or_used']);
			$inventory->setUnitPrice($value['unit_price']);
			$inventory->setBindId($value['bind_id']);
			$inventory->setDescription($value['description']);
			$inventory->setRemarks($value['remarks']);
			$inventory->setBulk($value['bulk']);
			$inventory->setIsRetain($value['is_retain']);
			$inventory->setIsStockRoom($value['is_stock_room']);
			$inventory->setDateCreated(new \DateTime($value['date_created']));
			$inventory->setMyCost($value['my_cost']);
			$inventory->setSaleRate($value['sale_rate']);
			$inventory->setTierQuantity1($value['tier_quantity1']);
			$inventory->setTierPrice1($value['tier_price1']);
			$inventory->setTierQuantity2($value['tier_quantity2']);
			$inventory->setTierPrice2($value['tier_price2']);
			$inventory->setTierQuantity3($value['tier_quantity3']);
			$inventory->setTierPrice3($value['tier_price3']);
			$inventory->setMyWeight($value['my_weight']);
			$inventory_list[$inventory->getInventoryId()] = $inventory;
			array_push($inventory_id_list, $inventory->getInventoryId());
		}

		$db_inv_list = $inventoryRepository->findAll();

		for ($i=0; $i < count($db_inv_list); $i++)
		{
			if (array_key_exists($db_inv_list[$i]->getInventoryId(), $inventory_list))
			{
				$updated = $db_inv_list[$i]->update($inventory_list[$db_inv_list[$i]->getInventoryId()]);
				if (count($updated) > 0)
				{
					// updating existing invs (if needed);
					$inventoryRepository->add($db_inv_list[$i]);
					// array_push($inv_updated, $updated);
					$inv_updated = array_merge($inv_updated, $updated);
				}
			}
			else
			{
				// removing unused invs;
				$inventoryRepository->remove($db_inv_list[$i]);

templates/inventory/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello InventoryController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Hello {{ controller_name }}! ✅</h1>

    This friendly message is coming from:
    <ul>
        <li>Your controller at <code><a href="{{ 'C:/xampp/htdocs/republika/smproject/src/Controller/InventoryController.php'|file_link(0) }}">src/Controller/InventoryController.php</a></code></li>
        <li>Your template at <code><a href="{{ 'C:/xampp/htdocs/republika/smproject/templates/inventory/index.html.twig'|file_link(0) }}">templates/inventory/index.html.twig</a></code></li>
    </ul>
</div>
{% endblock %}

templates/inventory/pull.html.twig
{% extends 'base_menu.html.twig' %}

{% block title %}Pull Bricklink Inventory {% endblock %}

{% block body %}
    <a href="{{ path('app_dashboard') }}" class="btn btn-primary m-2">back to list</a>
    <div class="container">
        <div class="m-auto text-center">
            {% if error %}
                <h2>Error occured</h2>
                <p>Message: {{ error.message }}</p>
                <p>Description: {{ error.description }}</p>
            {% else %}
                <p>{{ updated_items }} items has been added/updated</p>
                {% if updated_invs is not same as(null) %}
                    <p>{{ updated_invs }} inventories has been updated </p>
                {% else %}
                    <p>{{ added }} inventories has been added </p>
                    <p>{{ updated }} inventories has been updated </p>
                    <p>{{ removed }} inventories has been removed </p>
                    {% if update_logs or removed_logs %}
                    <h4>Changelogs</h4>
                    <ul class="list-group list-group-flush">
                        {% for log in update_logs %}
                            <li class="list-group-item">{{ log }}</li>
                        {% endfor %}
                        {% for log in removed_logs %}
                            <li class="list-group-item">{{ log[1] }}</li>
                        {% endfor %}
                    </ul>
                    {% endif %}
                {% endif %}
                {# <ul>
                    {{ dump(inventories) }}
                </ul> #}
            {% endif %}
        </div>
    </div>
        
{% endblock %}

templates/inventory/show.html.twig
{% extends 'base_menu.html.twig' %}

{% block title %}Inventory {{ inventory.id }}{% endblock %}

{% block body %}
    <a href="{{ path('app_dashboard') }}" class="btn btn-primary m-2">back to list</a>
    <div class="container">
        <h1>Inventory {{ inventory.inventoryId }}</h1>

        <div class="row align-items-start">
            <div class="col">
                <img src= '{{inventory.imageUrl}}' ></p>
            </div>

            <div class="col">
                <h2>Item information</h2>

                <div class="row align-items-start">
                    <div class="col">
                        Item number: 
                    </div>
                    <div class="col">
                        {{ inventory.Item.no }}
                    </div>
                </div>

                <div class="row align-items-start">
                    <div class="col">
                        Item name: 
                    </div>
                    <div class="col">
                        {{ inventory.Item.name }}
                    </div>
                </div>

                <div class="row align-items-start">
                    <div class="col">
                        Item type: 
                    </div>
                    <div class="col">
                        {{ inventory.item.Type }}
                    </div>
                </div>

                <div class="row align-items-start">
                    <div class="col">
                        Color name: 
                    </div>
                    <div class="col">
                        {{ inventory.colorName }}
                    </div>
                </div>

            </div>

            <div class="col">
                <h2>Lot information</h2>

                <div class="row align-items-start">
                    <div class="col">
                        Unit price: 
                    </div>
                    <div class="col">
                        {{ inventory.unitPrice }}
                    </div>
                </div>

                <div class="row align-items-start">
                    <div class="col">
                        Quantity: 
                    </div>
                    <div class="col">
                        {{ inventory.quantity }}
                    </div>
                </div>

                <div class="row align-items-start">
                    <div class="col">
                        Condition: 
                    </div>
                    <div class="col">
                        {{ inventory.newOrUsed }}
                    </div>
                </div>

                <div class="row align-items-start">
                    <div class="col">
                        Sale rate: 
                    </div>
                    <div class="col">
                        {{ inventory.saleRate }}
                    </div>
                </div>
                <div class="row align-items-start">
                    <div class="col">
                        Completeness:
                    </div>
                        <div class="col">
                        {% if inventory.completeness %}
                        {{ inventory.completeness }}
                        {% else %}
                            <span>NULL</span>
                        {% endif %}
                    </div>
                </div>

            </div>
        </div>
        
{% endblock %}